INTENTS = ("trend", "sentiment", "competitor", "unknown")
INTENT_CONFIDENCE_THRESHOLD = 0.5

REDDIT_FETCH_LIMIT = 40
REDDIT_TOP_N = 20
REDDIT_MIN_SCORE = 1
REDDIT_TIME_FILTER = "month"

SYNTHESIS_TOP_POSTS = 10
SYNTHESIS_SOURCE_COUNT = 5
